Practico01_G02L/Models/Alumno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace Practico01_G02L.Models
{
    public class Alumno
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }

        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Fechanacimiento { get; set; }
        public string Sexo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }

        [Display(Name = "Grado")]
        public int Idgrado { get; set; }

        [Display(Name = "Sección")]
        public int IdSeccion { get; set; }


    }
}

Practico01_G02L/Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Practico01_G02L.Models;

namespace Practico01_G02L.Controllers
{
    public class AlumnosController : Controller
    {
        private EscuelaDBContext db = new EscuelaDBContext();


        // GET: Alumnos
        public ActionResult Index(string BuscarNombre, int? grado=null, int? seccion=null)
        {


            List<Grado> listGrado = null;
            listGrado = db.Grados.ToList();

            List<SelectListItem> igrado = listGrado.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.itemgrado = igrado;


            List<Seccion> listSeccion = null;
            listSeccion = db.Secciones.ToList();

            List<SelectListItem> iseccion = listSeccion.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.itemseccion = iseccion;


            var alumnos = from p in db.Alumnos
                          select p;

            if (!String.IsNullOrEmpty(BuscarNombre))
            {
                alumnos = alumnos.Where(s => s.Nombres.Contains(BuscarNombre));
            }
            if (grado!=null)
            {
                alumnos = alumnos.Where(s => s.Idgrado==grado);
            }
            if (seccion!=null)
            {
                alumnos = alumnos.Where(s => s.IdSeccion == seccion);
            }
           // return View(db.Alumnos.ToList());
            return View(alumnos);
        }

        public ActionResult ViewNotes()
        {

             return View(db.Notas.ToList());            
        }

        // GET: Alumnos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnos.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        public ActionResult InsertNotes(int? id)
        {
            List<Materia> listMateria = null;
            listMateria = db.Materias.ToList();

            List<SelectListItem> imateria = listMateria.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.itemmateria = imateria;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnos.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            
         
            return View(alumno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult InsertNotes([Bind(Include = "Idalumno,idmateria,nota1,nota2,nota3,periodo")] Nota nota)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Notas.Add(nota);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(nota);
        //}
        public ActionResult InsertNotes(int Id, int idmateria, decimal nota1, decimal nota2, decimal nota3, decimal periodo)
        {
            Nota nota = new Nota();
            nota.IdAlumno = Id;
            nota.IdMateria = idmateria;
            nota.Nota1 = nota1;
            nota.Nota2 = nota2;
            nota.Nota3 = nota3;
            nota.Periodo = periodo;
            if (ModelState.IsValid)
            {
                db.Notas.Add(nota);
                db.SaveChanges();
                return RedirectToAction("ViewNotes");
            }

            return View(nota);
        }

        // GET: Alumnos/Create
        public ActionResult Create()
        {
            List<Grado> listGrado = null;
            listGrado = db.Grados.ToList();

            List<SelectListItem> igrado = listGrado.ConvertAll(d =>
           {
               return new SelectListItem()
               {
                   Text = d.Nombre.ToString(),
                   Value = d.Id.ToString(),
                   Selected = false
               };
           });

            ViewBag.itemgrado = igrado;

            List<Seccion> listSeccion = null;
            listSeccion = db.Secciones.ToList();

            List<SelectListItem> iseccion = listSeccion.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.itemseccion = iseccion;

            return View();
        }

        // POST: Alumnos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombres,Apellidos,Fechanacimiento,Sexo,Direccion,Telefono,Idgrado,IdSeccion")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                db.Alumnos.Add(alumno);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(alumno);
        }

        // GET: Alumnos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnos.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }

            List<Grado> listGrado = null;
            listGrado = db.Grados.ToList();

            List<SelectListItem> igrado = listGrado.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.itemgrado = igrado;

            List<Seccion> listSeccion = null;
            listSeccion = db.Secciones.ToList();

            List<SelectListItem> iseccion = listSeccion.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                    Selected = false
                };
            });

            ViewBag.itemseccion = iseccion;
            return View(alumno);
        }

        // POST: Alumnos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombres,Apellidos,Fechanacimiento,Sexo,Direccion,Telefono,Idgrado,IdSeccion")] Alumno alumno)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alumno).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(alumno);
        }

        // GET: Alumnos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alumno alumno = db.Alumnos.Find(id);
            if (alumno == null)
            {
                return HttpNotFound();
            }
            return View(alumno);
        }

        // POST: Alumnos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alumno alumno = db.Alumnos.Find(id);
            db.Alumnos.Remove(alumno);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Practico01_G02L/Views/Alumnos/Create.cshtml
@model Practico01_G02L.Models.Alumno

@{
    ViewBag.Title = "Create";
    List<SelectListItem> igrado = (List<SelectListItem>)ViewBag.itemgrado;
    List<SelectListItem> iseccion = (List<SelectListItem>)ViewBag.itemseccion;
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fechanacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fechanacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fechanacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idgrado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.Idgrado, igrado,"Grados", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdSeccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.DropDownListFor(model => model.IdSeccion, iseccion, "Secciones", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practico01_G02L/Views/Alumnos/Delete.cshtml
@model Practico01_G02L.Models.Alumno

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fechanacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fechanacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idgrado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idgrado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdSeccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSeccion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Practico01_G02L/Views/Alumnos/Details.cshtml
@model Practico01_G02L.Models.Alumno

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fechanacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fechanacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idgrado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idgrado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdSeccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSeccion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Practico01_G02L/Views/Alumnos/Edit.cshtml
@model Practico01_G02L.Models.Alumno

@{
    ViewBag.Title = "Edit";
    List<SelectListItem> igrado = (List<SelectListItem>)ViewBag.itemgrado;
    List<SelectListItem> iseccion = (List<SelectListItem>)ViewBag.itemseccion;
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fechanacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fechanacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fechanacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idgrado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Idgrado, igrado, "Grados", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdSeccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IdSeccion, iseccion, "Secciones", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practico01_G02L/Views/Alumnos/Index.cshtml
@model IEnumerable<Practico01_G02L.Models.Alumno>

@{
    ViewBag.Title = "Index";
    List<SelectListItem> igrado = (List<SelectListItem>)ViewBag.itemgrado;
    List<SelectListItem> iseccion = (List<SelectListItem>)ViewBag.itemseccion;
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm("Index", "Alumnos", FormMethod.Get))
    {

    <p>
        Titulo: @Html.TextBox("BuscarNombre") <br />
        @Html.DropDownList("grado", igrado, "Grados", new { htmlAttributes = new { @class = "form-control" } })
        @Html.DropDownList("seccion", iseccion, "Secciones", new { htmlAttributes = new { @class = "form-control" } })
        <input type="submit" value="Filtrar" />
    </p>

}
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombres)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fechanacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idgrado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSeccion)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombres)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellidos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fechanacimiento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sexo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idgrado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdSeccion)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Notas", "InsertNotes", new { id = item.Id })
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

Practico01_G02L/Views/Alumnos/InsertNotes.cshtml
@model Practico01_G02L.Models.Alumno

@{
    ViewBag.Title = "Insertar Notas";
    List<SelectListItem> imateria = (List<SelectListItem>)ViewBag.itemmateria;

}

<h2>Insertar Notas</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Alumno</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)


    <div class="form-group">
        @Html.Label("Id alumno", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, "", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("idalumno", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Materia", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idmateria", imateria, "Materias", new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Nota 1", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("nota1", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("Nota 1", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Nota 2", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("nota2", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("Nota 2", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Nota 3", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("nota3", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("Nota 3", "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Periodo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.Editor("periodo", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessage("Periodo", "", new { @class = "text-danger" })
        </div>
    </div>




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practico01_G02L/Views/Alumnos/ViewNotes.cshtml
@model IEnumerable<Practico01_G02L.Models.Nota>

@{
    ViewBag.Title = "Notas";

}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Idnota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdAlumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdMateria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nota3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Periodo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Idnota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdAlumno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdMateria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nota1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nota2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nota3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Periodo)
                </td>
                <td>

                </td>
            </tr>
        }

    </table>